#server:
#  port: 6128
spring:
  application:
    name: blps_1
  datasource:
    jndi-name: "java:jboss/datasources/blps"
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
springdoc:
  swagger-ui:
    operations-sorter: method
    defaultModelsExpandDepth: -1
    tags-sorter: alpha
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
logging:
  level:
    root: info